- name: Get HDB server version
  ansible.builtin.shell: "grep fullversion {{software_location}}/server/manifest"
  register: getversiononshare
  check_mode: no # run in check mode
  changed_when: 0 # don't show as changed
  become: true
  become_user: "{{sap_sid}}adm"
  
- fail: 
    msg: "SAP HANA Server software not found. Aborting. Fail."
  when: not target_version in getversiononshare.stdout