- block:
    - name: Login with username and new password
      ansible.builtin.command: >
        {{ hdb_exe }}/hdbsql -i {{ hana_instance_nr }} 
        -d SYSTEMDB 
        -u {{ hana_update_user }} -p {{ hana_update_user_password }} 
        {{ secure }} -a -x "select * from M_DATABASES"
      vars:
          hdb_exe: "/usr/sap/{{ sap_sid | upper }}/HDB{{ hana_instance_nr }}/exe"
      become: true
      become_user: "{{ sap_sid | lower }}adm"
      register: command_result
      ignore_errors: yes

    - set_fact:
        custom_change_summary: "{{ custom_change_summary | default([]) + [ message ] }}"
      vars:
        message: "ERROR: Update user {{ hana_update_user }} could not log into SYSTEMDB"

    - name: Display fatal error if update user cannot login
      fail:
        msg: "Update user {{ hana_update_user }} could not log into SYSTEMDB and cannot perform the upgrade"
      when: command_result.rc != 0
  check_mode: false # run in check mode