---
- name: Decide if HDB client needs a patch
  block:
    - name: Get HDB client version
      shell: "{{grep_command}}"
      register: getclientversion
      vars:
        grep_command: "grep fullversion {{hdbclient_location}}/manifest | awk '{ print $NF }' | awk {{awk}} "
        awk: -F "." '{print $1"."$2"."$3}'
      check_mode: no # run in check mode
      changed_when: 0 # don't show as changed
      
    - ansible.builtin.debug: 
        msg: "SAP HANA Client needs a patch. From: {{found_version}}  to: {{target_version}} "
      when: not target_version in found_version
    - name: Report - Store action in variable
      ansible.builtin.set_fact:
        custom_change_summary:
          "Patch SAP HANA Client on {{inventory_hostname}} from {{found_version}} to {{target_version}}"
      check_mode: false # run in check mode      
      when: not target_version in found_version
    - name: patchen client
      include_tasks: patchen-client.yml
      when: not target_version in found_version
  vars:
    found_version: "{{ getclientversion.stdout | default('0.0') }}"
