---

- include_tasks: backup_location.yml
  when: 
    - backup_type == 'file'

- include_tasks: perform_backup.yml
  vars:
    backup_method: FILE
    backup_name: "{{ backup_location ~ '/' ~ backup_filename ~ '/' }}"
  when: 
    - backup_type == 'file'    

- include_tasks: perform_backup.yml
  vars:
    backup_method: BACKINT
    timestamp: "{{ lookup('pipe', 'date +\"%Y%m%d%H%M%S\"') }}"
    backup_name: "{{ timestamp }}/"
  when: 
    - backup_type == 'backint'    
