- block:
- name: Inform user that restore will be started
  debug:
    msg: |
      --------------------------------------------------------------------
            
            The restore will be started in the next step. 

            Take a break.

      --------------------------------------------------------------------
  when: not ansible_check_mode

- name: Perform stop database
  shell: "{{ backup_command }}"
  vars:
    secure_params: >-
      {%- if secure_connection -%}
      -e -ssltrustcert
      {%- endif -%}
    backup_command: >-
      source ~/.sapenv.sh && hdbsql {{ secure_params }} -i {{ instance_nr }} -U {{ hdbsql_key }} "{{ sql }}"
    sql: "ALTER SYSTEM STOP DATABASE {{ hdb_db | upper }}"
  become: true
  become_user: "{{ hdb_db | lower }}adm"


# - name: Perform restore
#   shell: "{{ backup_command }}"
#   vars:
#     secure_params: >-
#       {%- if secure_connection -%}
#       -e -ssltrustcert
#       {%- endif -%}
#     backup_command: >-
#       source ~/.sapenv.sh && hdbsql {{ secure_params }} -i {{ instance_nr }} -U {{ hdbsql_key }} "{{ item }}"
#   loop:
#     - "ALTER SYSTEM STOP DATABASE {{ hdb_db | upper }}"
#     - "RECOVER DATA FOR {{ hdb_db | upper }} USING FILE ('{{ backup_path }}') CLEAR LOG"
#   become: true
#   become_user: "{{ hdb_db | lower }}adm"
