- name: Inform user that restore will be started
  ansible.builtin.debug:
    msg: |
      --------------------------------------------------------------------

            The restore will be started in the next step.

            Take a break.

      --------------------------------------------------------------------
  when: not ansible_check_mode

- name: Perform restore database
  ansible.builtin.shell: "{{ backup_command }}"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ hdb_db | lower }}adm"
  vars:
    secure_params: >-
      {%- if secure_connection -%}
      -e -ssltrustcert{%- endif -%}
    backup_command: |
      /usr/sap/{{ hdb_sid | upper }}/HDB{{ instance_nr }}/exe/hdbsql {{ secure_params }} -U {{ hdbsql_key }} "{{ sql }}"
    sql: |
      RECOVER DATA FOR {{ hdb_db | upper }} USING FILE ('{{ backup_path }}') CLEAR LOG
