- name: Stop SAP Instance
  ansible.builtin.shell: "source ~/.sapenv.sh && sapcontrol -nr {{ instance_nr }} -function Stop"
  become: true
  become_user: "{{ hdb_sid }}adm"
  args:
    executable: /bin/bash

- name: Wait for stopped
  ansible.builtin.shell: "source ~/.sapenv.sh && sapcontrol -nr {{ instance_nr }} -function WaitforStopped {{ waittimeout }} 2"
  register: outs
  become: true
  become_user: "{{ hdb_sid }}adm"
  args:
    executable: /bin/bash

- name: Debug output
  ansible.builtin.debug: var=outs
